dist: xenial
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - easy_install Cython

install: 
  - (cd docs && pip install -r requirements.txt)
  - python setup.py build_ext -i

script:
  - nosetests --with-doctest tess
  - (cd docs && make doctest)